# Generated by Django 5.1.4 on 2024-12-16 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('fuel', models.CharField(choices=[('benzin', 'бензин'), ('gaz', 'газ'), ('dizil', 'дизель'), ('electro', 'електричество')], max_length=10)),
                ('date', models.DateField()),
                ('trasmission', models.CharField(choices=[('mehanic', 'механика'), ('automat', 'автомат'), ('robot', 'робот')], max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpr.brend')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpr.model')),
            ],
        ),
    ]
